### ISSUE TITLE
Create Intro Page

### ISSUE THREAD

**Issue by kchanba** [NYCPlanning/ceqr-app#491]
Welcome to CEQR :sparkles::rainbow::cityscape:

**Comment by trbmcginnis** [comment]
![Screen Shot 2019-12-23 at 4.40.45 PM.png](https://images.zenhubusercontent.com/5ca36b1555cfe32f2f66b411/7864c552-5634-402a-bc96-9750a83b37f6)

**Comment by trbmcginnis** [comment]
![Screen Shot 2019-12-23 at 4.41.12 PM.png](https://images.zenhubusercontent.com/5ca36b1555cfe32f2f66b411/7db58990-2944-4313-9720-6a97ced1c0a4)

**Comment by trbmcginnis** [comment]
This page should appear every time a new user logs in. A new user is defined as someone who has logged in for the first time and has just confirmed their email. in `templates/signup/email.hbs` there is a link to the `login` route. With query params `firstLogin=true`, this will reroute the user to the intro page route. Otherwise if `firstLogin=false` then a user will be routed to `routes/user/projects`

**Comment by allthesignals** [comment]
@trbmcginnis i'm closing this for now, let me know if it needs t obe reopened
