### ISSUE TITLE
Remove "sca_enrollment_pct_by_sd" table

### ISSUE THREAD

**Issue by bfreeds** [NYCPlanning/ceqr-app#637]
Currently this table of percentages is brought into the rails application to be used in the multipliers to calculate projected enrollment.  

With EDM taking ownership over the data pipelines, they will include this calculation in their pipeline, giving us a table that's precalculated.  

We need to remove this table from `ceqr_data` database, and all associated logic, wherever this information is currently being used in the app.  EDM will be updating this for retroactive data packages (2017 & 2018) as well.  

**Note** we use `ceqr_data` db for development, staging, and production.  So we don't want to remove this table from the db until all the logic in the app has already been updated & the new data is fully implemented.

Related to #484

**Comment by trbmcginnis** [comment]
For frontend changes:

In the backend, these percentages are saved as `futureEnrollmentMultipliers`. 

In `public-schools-analysis.js` model, there are two multiplier attributes coming from the backend: `multiplier` and `futureEnrollmentMultipliers`. 

`multiplier` refers to the constant that we multiply by the # of net units to determine how many new residents are likely to be school age children. 

`futureEnrollmentMultipliers` refers to the percentage that we multiply by `sca_enrollment_projection` district student values to get the distribution of students in each subdistrict. Example: If there are 1,000 students in a district, and the `futureEnrollmentMultiplier` for ps schools in district 1 subdistrict 2 is 50%, then the number of students in that subdistrict would be 500 students. 

In the frontend `public-schools-analysis.js` model, under the `subdistrictTotals` computed property, we define `enroll` (for ps and ms schools in different calculations) as the `futureEnrollmentProjections` * `futureEnrollmentMultipliers` to get the enrollment for a subdistrict. Because EDM is now doing this calculation in the database, we no longer need to do this calculation in the frontend, and `futureEnrollmentMultipliers` can be removed from this model.

**Comment by trbmcginnis** [comment]
**Subdistricts (ps, is)**
Before EDM made their changes, we had a table in the database called `sca_enrollment_projections_by_sd`. This name is incorrect, as the table only has a column for district, not subdistrict. 

The future table called `sca_enrollment_projections_by_sd` will correctly reflect the district enrollment projections multiplied by the enrollment percentages for subdistricts.

**Boroughs (hs)**
Before EDM made their changes, we had a table in the database called `sca_enrollment_projections_by_boro`. This table provides the correct data. EDM will change the borough name to borough code.
