### ISSUE TITLE
Users can't click on or edit projects

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/ceqr-app#659]
We had a user report that she can see a list of her projects when logging into the app, but she can’t click them open. Kasia also reproduced this. She created a test project and it wouldn’t open when she clicked on it, or when she clicked on the edit button.

This is a critical bug because it prevents users from working on their projects.

Steps to reproduce:
- Login
- Create a project
- Go back to dashboard and try to click on project
- See that the project doesn't open

**Comment by bfreeds** [comment]
@godfreyyeung on production I created a new test project.  This is the error message I received when I tried to edit that project and click `Save`.  
![image.png](https://images.zenhubusercontent.com/5dd5a1e7efbeb900016c9ffd/5e658ad8-ddb6-4852-a737-af2300ac95d1)

Note that I wasn't able to replicate the issue of not being able to go to the dashboard then back into an existing project -- that seemed to work OK for me.

**Comment by godfreyyeung** [comment]
I also wasn't able to reproduce "not being able to open a project" on either staging or production. However, l was able to reproduce not being able to save edits to a project:
   1. Click "edit" on a project
   2. Make edits (adjust numbers)
   3. Click save. There will be no effect.

**Comment by godfreyyeung** [comment]
![ceqr-aq-error](https://user-images.githubusercontent.com/3311663/75586363-40386300-5a42-11ea-887f-c1e0dd084942.png)

The backend error occurring during Project editing related to Air Quality Analysis. Thus the proposed hotfix is to remove all Air Quality Analysis code, since it isn't used (yet). See #663

**Comment by godfreyyeung** [comment]
After deploying the hotfix involving removing Air Quality Analysis, getting mixed results:
  - New projects can be edited
  - Some old projects still cannot be opened or edited

**Comment by bfreeds** [comment]
@godfreyyeung were you able to confirm that the old projects can't be opened or edited at all, or were these users experiencing very slow response times (over 1 minute)?

**Comment by godfreyyeung** [comment]
## Investigation notes

For Kasia's test project 980, opening, opening for editing, and saving edits always results in long request times. When testing it locally, regardless if using Docker, about half the time one of those requests will also generate the error `PQconsumeInput() SSL SYSCALL error: EOF detected`. 

The stack trace eventually traces it to two functions, 
  - /app/interfaces/ceqr_data/mappluto.rb `st_union_bbls`
  - /app/models/project.rb  - `set_bbl_attributes`

These two functions take the Project's selected BBLs and grabs their geometries from the versino of Mappluto selected by the Datapackage.

Perhaps the problem is that the selected BBLs for the project has very complex geometries, or perhaps there was recently updates to Mappluto creating more complex geometries, or edited the geometry design.
